POST localhost:8081/order
Content-Type: application/json

{
    "userId": 123,
    "symbol": "BTC/USD",
    "orderType": "LIMIT",
    "side": "BUY",
    "price": 30000,
    "quantity": 0.5,
    "clientOrderId": "123456"
}
